#include <cstring>
#include <boost/filesystem.hpp>
#include <ogr_api.h>
#include <ogr_spatialref.h>
#include "XMLHandler.h"
#include <list>
#include <omp.h>
#include <cstdio>
#include <iostream>
#include <ctime>
#include <map>
#include "SOIL.h"
#include <cassert>
#include "mat.h"
#include "shapefil.h"
#include "polypartition.h"
#include <boost/test/unit_test.hpp>
#include <memory>
#include <vector>
